#!/usr/bin/env bash
set -e
NB=/home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox

# Overlap 0
conda run -n FCL python3 /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/core_modules/run_advanced_experiments.py --single --model-size tiny --overlap 0 --loss "Sinkhorn_0.15xKL" --epochs 200 --topology-n-jobs 1 --wandb --output-dir /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/experiments
conda run -n FCL python3 /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/core_modules/run_advanced_experiments.py --single --model-size tiny --overlap 0 --loss "PersLandscape" --epochs 200 --topology-n-jobs 1 --wandb --output-dir /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/experiments
conda run -n FCL python3 /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/core_modules/run_advanced_experiments.py --single --model-size tiny --overlap 0 --loss "DiffPers" --epochs 200 --topology-n-jobs 1 --wandb --output-dir /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/experiments
conda run -n FCL python3 /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/core_modules/run_advanced_experiments.py --single --model-size tiny --overlap 0 --loss "RTD" --epochs 200 --topology-n-jobs 1 --wandb --output-dir /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/experiments
conda run -n FCL python3 /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/core_modules/run_advanced_experiments.py --single --model-size tiny --overlap 0 --loss "LW_DiffPers" --epochs 200 --topology-n-jobs 1 --wandb --output-dir /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/experiments
conda run -n FCL python3 /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/core_modules/run_advanced_experiments.py --single --model-size tiny --overlap 0 --loss "LW_RTD" --epochs 200 --topology-n-jobs 1 --wandb --output-dir /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/experiments
conda run -n FCL python3 /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/core_modules/run_advanced_experiments.py --single --model-size tiny --overlap 0 --loss "MSE+0.1*DiffPers" --epochs 200 --topology-n-jobs 1 --wandb --output-dir /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/experiments
conda run -n FCL python3 /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/core_modules/run_advanced_experiments.py --single --model-size tiny --overlap 0 --loss "MAE+0.1*DiffPers" --epochs 200 --topology-n-jobs 1 --wandb --output-dir /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/experiments
conda run -n FCL python3 /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/core_modules/run_advanced_experiments.py --single --model-size tiny --overlap 0 --loss "MSE+0.05*RTD" --epochs 200 --topology-n-jobs 1 --wandb --output-dir /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/experiments
conda run -n FCL python3 /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/core_modules/run_advanced_experiments.py --single --model-size tiny --overlap 0 --loss "MAE+0.05*RTD" --epochs 200 --topology-n-jobs 1 --wandb --output-dir /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/experiments
conda run -n FCL python3 /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/core_modules/run_advanced_experiments.py --single --model-size tiny --overlap 0 --loss "LW_MSE+0.1*LW_DiffPers" --epochs 200 --topology-n-jobs 1 --wandb --output-dir /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/experiments
conda run -n FCL python3 /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/core_modules/run_advanced_experiments.py --single --model-size tiny --overlap 0 --loss "LW_MAE+0.1*LW_DiffPers" --epochs 200 --topology-n-jobs 1 --wandb --output-dir /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/experiments
conda run -n FCL python3 /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/core_modules/run_advanced_experiments.py --single --model-size tiny --overlap 0 --loss "LW_MSE+0.05*LW_RTD" --epochs 200 --topology-n-jobs 1 --wandb --output-dir /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/experiments
conda run -n FCL python3 /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/core_modules/run_advanced_experiments.py --single --model-size tiny --overlap 0 --loss "PersImage" --epochs 200 --topology-n-jobs 1 --wandb --output-dir /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/experiments
conda run -n FCL python3 /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/core_modules/run_advanced_experiments.py --single --model-size tiny --overlap 0 --loss "Sinkhorn+0.1*DiffPers" --epochs 200 --topology-n-jobs 1 --wandb --output-dir /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/experiments

# Overlap 1
conda run -n FCL python3 /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/core_modules/run_advanced_experiments.py --single --model-size tiny --overlap 1 --loss "Huber" --epochs 200 --topology-n-jobs 1 --wandb --output-dir /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/experiments
conda run -n FCL python3 /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/core_modules/run_advanced_experiments.py --single --model-size tiny --overlap 1 --loss "CosineLoss" --epochs 200 --topology-n-jobs 1 --wandb --output-dir /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/experiments
conda run -n FCL python3 /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/core_modules/run_advanced_experiments.py --single --model-size tiny --overlap 1 --loss "Sinkhorn_0.15xKL" --epochs 200 --topology-n-jobs 1 --wandb --output-dir /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/experiments
conda run -n FCL python3 /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/core_modules/run_advanced_experiments.py --single --model-size tiny --overlap 1 --loss "PersLandscape" --epochs 200 --topology-n-jobs 1 --wandb --output-dir /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/experiments
conda run -n FCL python3 /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/core_modules/run_advanced_experiments.py --single --model-size tiny --overlap 1 --loss "DiffPers" --epochs 200 --topology-n-jobs 1 --wandb --output-dir /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/experiments
conda run -n FCL python3 /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/core_modules/run_advanced_experiments.py --single --model-size tiny --overlap 1 --loss "RTD" --epochs 200 --topology-n-jobs 1 --wandb --output-dir /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/experiments
conda run -n FCL python3 /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/core_modules/run_advanced_experiments.py --single --model-size tiny --overlap 1 --loss "LW_DiffPers" --epochs 200 --topology-n-jobs 1 --wandb --output-dir /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/experiments
conda run -n FCL python3 /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/core_modules/run_advanced_experiments.py --single --model-size tiny --overlap 1 --loss "LW_RTD" --epochs 200 --topology-n-jobs 1 --wandb --output-dir /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/experiments
conda run -n FCL python3 /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/core_modules/run_advanced_experiments.py --single --model-size tiny --overlap 1 --loss "MSE+0.1*DiffPers" --epochs 200 --topology-n-jobs 1 --wandb --output-dir /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/experiments
conda run -n FCL python3 /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/core_modules/run_advanced_experiments.py --single --model-size tiny --overlap 1 --loss "MAE+0.1*DiffPers" --epochs 200 --topology-n-jobs 1 --wandb --output-dir /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/experiments
conda run -n FCL python3 /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/core_modules/run_advanced_experiments.py --single --model-size tiny --overlap 1 --loss "MSE+0.05*RTD" --epochs 200 --topology-n-jobs 1 --wandb --output-dir /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/experiments
conda run -n FCL python3 /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/core_modules/run_advanced_experiments.py --single --model-size tiny --overlap 1 --loss "MAE+0.05*RTD" --epochs 200 --topology-n-jobs 1 --wandb --output-dir /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/experiments
conda run -n FCL python3 /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/core_modules/run_advanced_experiments.py --single --model-size tiny --overlap 1 --loss "LW_MSE+0.1*LW_DiffPers" --epochs 200 --topology-n-jobs 1 --wandb --output-dir /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/experiments
conda run -n FCL python3 /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/core_modules/run_advanced_experiments.py --single --model-size tiny --overlap 1 --loss "LW_MAE+0.1*LW_DiffPers" --epochs 200 --topology-n-jobs 1 --wandb --output-dir /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/experiments
conda run -n FCL python3 /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/core_modules/run_advanced_experiments.py --single --model-size tiny --overlap 1 --loss "LW_MSE+0.05*LW_RTD" --epochs 200 --topology-n-jobs 1 --wandb --output-dir /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/experiments
conda run -n FCL python3 /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/core_modules/run_advanced_experiments.py --single --model-size tiny --overlap 1 --loss "PersImage" --epochs 200 --topology-n-jobs 1 --wandb --output-dir /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/experiments
conda run -n FCL python3 /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/core_modules/run_advanced_experiments.py --single --model-size tiny --overlap 1 --loss "Sinkhorn+0.1*DiffPers" --epochs 200 --topology-n-jobs 1 --wandb --output-dir /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/experiments

# Overlap 2
conda run -n FCL python3 /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/core_modules/run_advanced_experiments.py --single --model-size tiny --overlap 2 --loss "Huber" --epochs 200 --topology-n-jobs 1 --wandb --output-dir /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/experiments
conda run -n FCL python3 /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/core_modules/run_advanced_experiments.py --single --model-size tiny --overlap 2 --loss "CosineLoss" --epochs 200 --topology-n-jobs 1 --wandb --output-dir /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/experiments
conda run -n FCL python3 /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/core_modules/run_advanced_experiments.py --single --model-size tiny --overlap 2 --loss "Sinkhorn_0.15xKL" --epochs 200 --topology-n-jobs 1 --wandb --output-dir /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/experiments
conda run -n FCL python3 /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/core_modules/run_advanced_experiments.py --single --model-size tiny --overlap 2 --loss "PersLandscape" --epochs 200 --topology-n-jobs 1 --wandb --output-dir /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/experiments
conda run -n FCL python3 /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/core_modules/run_advanced_experiments.py --single --model-size tiny --overlap 2 --loss "DiffPers" --epochs 200 --topology-n-jobs 1 --wandb --output-dir /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/experiments
conda run -n FCL python3 /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/core_modules/run_advanced_experiments.py --single --model-size tiny --overlap 2 --loss "RTD" --epochs 200 --topology-n-jobs 1 --wandb --output-dir /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/experiments
conda run -n FCL python3 /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/core_modules/run_advanced_experiments.py --single --model-size tiny --overlap 2 --loss "LW_DiffPers" --epochs 200 --topology-n-jobs 1 --wandb --output-dir /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/experiments
conda run -n FCL python3 /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/core_modules/run_advanced_experiments.py --single --model-size tiny --overlap 2 --loss "LW_RTD" --epochs 200 --topology-n-jobs 1 --wandb --output-dir /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/experiments
conda run -n FCL python3 /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/core_modules/run_advanced_experiments.py --single --model-size tiny --overlap 2 --loss "MSE+0.1*DiffPers" --epochs 200 --topology-n-jobs 1 --wandb --output-dir /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/experiments
conda run -n FCL python3 /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/core_modules/run_advanced_experiments.py --single --model-size tiny --overlap 2 --loss "MAE+0.1*DiffPers" --epochs 200 --topology-n-jobs 1 --wandb --output-dir /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/experiments
conda run -n FCL python3 /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/core_modules/run_advanced_experiments.py --single --model-size tiny --overlap 2 --loss "MSE+0.05*RTD" --epochs 200 --topology-n-jobs 1 --wandb --output-dir /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/experiments
conda run -n FCL python3 /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/core_modules/run_advanced_experiments.py --single --model-size tiny --overlap 2 --loss "MAE+0.05*RTD" --epochs 200 --topology-n-jobs 1 --wandb --output-dir /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/experiments
conda run -n FCL python3 /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/core_modules/run_advanced_experiments.py --single --model-size tiny --overlap 2 --loss "LW_MSE+0.1*LW_DiffPers" --epochs 200 --topology-n-jobs 1 --wandb --output-dir /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/experiments
conda run -n FCL python3 /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/core_modules/run_advanced_experiments.py --single --model-size tiny --overlap 2 --loss "LW_MAE+0.1*LW_DiffPers" --epochs 200 --topology-n-jobs 1 --wandb --output-dir /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/experiments
conda run -n FCL python3 /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/core_modules/run_advanced_experiments.py --single --model-size tiny --overlap 2 --loss "LW_MSE+0.05*LW_RTD" --epochs 200 --topology-n-jobs 1 --wandb --output-dir /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/experiments
conda run -n FCL python3 /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/core_modules/run_advanced_experiments.py --single --model-size tiny --overlap 2 --loss "PersImage" --epochs 200 --topology-n-jobs 1 --wandb --output-dir /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/experiments
conda run -n FCL python3 /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/core_modules/run_advanced_experiments.py --single --model-size tiny --overlap 2 --loss "Sinkhorn+0.1*DiffPers" --epochs 200 --topology-n-jobs 1 --wandb --output-dir /home/aymen/Documents/GitHub/Federated-Continual-learning-/New/notebooks_sandbox/experiments
